version: "3.9"

services:
  library-backend:
    container_name: library-backend
    build:
      context: ./server
    ports:
      - "3000:3000"
    restart: unless-stopped

  library-frontend:
    container_name: library-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:80"
    depends_on:
      - library-backend
    restart: unless-stopped
